=== brianchandotcom/liferay-portal/definitions/liferay-workflow-definition_7_4_0.xsd
<?xml version="1.0"?>

<xs:schema
	elementFormDefault="qualified"
	targetNamespace="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" />
	<xs:complexType abstract="true" name="abstract-notification-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element name="template" type="xs:string" />
			<xs:element name="template-language" type="template-language-type" />
			<xs:element maxOccurs="unbounded" name="notification-type" type="notification-transport-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType abstract="true" name="abstract-timer-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element name="delay" type="time-delay-complex-type" />
			<xs:element minOccurs="0" name="recurrence" type="time-delay-complex-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType abstract="true" name="abstract-workflow-node-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element minOccurs="0" name="metadata" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="action-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:choice maxOccurs="1" minOccurs="1">
				<xs:sequence>
					<xs:element name="script" type="xs:string" />
					<xs:element name="script-language" type="script-language-type" />
					<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
				</xs:sequence>
				<xs:element name="status" type="xs:int" />
			</xs:choice>
			<xs:element minOccurs="0" name="priority" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="action-timer-workflow-node-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-workflow-node-complex-type">
				<xs:sequence>
					<xs:element minOccurs="0" name="actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded" minOccurs="0">
								<xs:group ref="actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element minOccurs="0" name="timers">
						<xs:complexType>
							<xs:sequence>
								<xs:element maxOccurs="unbounded" name="timer" type="timer-complex-type" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="notification-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-notification-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="recipients" type="recipients-complex-type" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="recipients-complex-type">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="address" type="email-address-type" />
			<xs:element minOccurs="0" name="roles">
				<xs:complexType>
					<xs:choice minOccurs="0">
						<xs:element maxOccurs="unbounded" name="role" type="role-complex-type" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="scripted-recipient" type="script-complex-type" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="user" type="user-complex-type" />
		</xs:sequence>
		<xs:attribute default="to" name="receptionType" type="notification-reception-type" />
	</xs:complexType>
	<xs:complexType name="role-complex-type">
		<xs:sequence>
			<xs:choice>
				<xs:element minOccurs="0" name="role-id" type="xs:long" />
				<xs:sequence>
					<xs:element default="regular" minOccurs="0" name="role-type" type="role-type" />
					<xs:element minOccurs="0" name="name" type="xs:string" />
					<xs:element default="true" minOccurs="0" name="auto-create" type="xs:boolean" />
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="script-complex-type">
		<xs:sequence>
			<xs:element name="script" type="xs:string" />
			<xs:element name="script-language" type="script-language-type" />
			<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="task-form-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:choice maxOccurs="1">
				<xs:element name="form-definition" type="xs:string" />
				<xs:element name="form-reference">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="company-id" type="xs:long" />
							<xs:element name="form-id" type="xs:long" />
							<xs:element name="form-uuid" type="xs:string" />
							<xs:element name="group-id" type="xs:long" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element minOccurs="0" name="metadata" type="xs:string" />
			<xs:element name="priority" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="task-notification-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-notification-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="recipients" type="task-recipients-complex-type" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="task-recipients-complex-type">
		<xs:complexContent>
			<xs:extension base="recipients-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="1" minOccurs="0" name="assignees">
						<xs:complexType />
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="task-timer-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-timer-complex-type">
				<xs:sequence>
					<xs:element default="false" minOccurs="0" name="blocking" type="xs:boolean" />
					<xs:element name="timer-actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
								<xs:group ref="task-timer-actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="time-delay-complex-type">
		<xs:sequence>
			<xs:element name="duration" type="xs:double" />
			<xs:element name="scale" type="time-scale-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="timer-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-timer-complex-type">
				<xs:sequence>
					<xs:element minOccurs="0" name="timer-actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
								<xs:group ref="timer-actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="user-complex-type">
		<xs:choice>
			<xs:element minOccurs="0" name="user-id" type="xs:long" />
			<xs:element minOccurs="0" name="screen-name" type="xs:string" />
			<xs:element minOccurs="0" name="email-address" type="email-address-type" />
		</xs:choice>
	</xs:complexType>
	<xs:element name="ai-decision">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="input-variables" type="xs:string" />
						<xs:element minOccurs="0" name="output-variables" type="xs:string" />
						<xs:element name="prompt" type="xs:string" />
						<xs:element minOccurs="0" name="tools" type="xs:string" />
						<xs:element minOccurs="0" ref="transitions" />
						<xs:element name="user-message" type="xs:string" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element name="script" type="xs:string" />
						<xs:element name="script-language" type="script-language-type" />
						<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fork">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="join">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="join-xor">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="labels">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="label">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="language-id" type="xs:string" use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="llm">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="input-variables" type="xs:string" />
						<xs:element minOccurs="0" name="output-variables" type="xs:string" />
						<xs:element name="prompt" type="xs:string" />
						<xs:element minOccurs="0" name="tools" type="xs:string" />
						<xs:element minOccurs="0" ref="transitions" />
						<xs:element name="user-message" type="xs:string" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="state">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element default="false" minOccurs="0" name="initial" type="xs:boolean" />
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="task">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" name="actions">
							<xs:complexType>
								<xs:choice>
									<xs:group maxOccurs="unbounded" ref="task-actions-group" />
								</xs:choice>
							</xs:complexType>
						</xs:element>
						<xs:element name="assignments">
							<xs:complexType>
								<xs:choice>
									<xs:group ref="assignments-group" />
								</xs:choice>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="task-forms">
							<xs:complexType>
								<xs:sequence>
									<xs:element maxOccurs="unbounded" name="task-form" type="task-form-complex-type" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" name="task-timers">
							<xs:complexType>
								<xs:sequence>
									<xs:element maxOccurs="unbounded" name="task-timer" type="task-timer-complex-type" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="transitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="transition">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" ref="labels" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="target" type="xs:string" />
							<xs:element default="true" minOccurs="0" name="default" type="xs:boolean" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="workflow-definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="name" type="xs:string" />
				<xs:element minOccurs="0" name="description" type="xs:string" />
				<xs:element minOccurs="0" name="version" type="xs:int" />
				<xs:group maxOccurs="unbounded" ref="nodes-group" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="actions-group">
		<xs:choice>
			<xs:element name="action">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="action-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notification">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="notification-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="assignments-group">
		<xs:choice>
			<xs:element name="resource-actions">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="resource-action" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="roles">
				<xs:complexType>
					<xs:choice minOccurs="0">
						<xs:element maxOccurs="unbounded" name="role" type="role-complex-type" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="scripted-assignment" type="script-complex-type" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="user" type="user-complex-type" />
		</xs:choice>
	</xs:group>
	<xs:group name="nodes-group">
		<xs:choice>
			<xs:element ref="ai-decision" />
			<xs:element ref="condition" />
			<xs:element ref="fork" />
			<xs:element ref="join" />
			<xs:element ref="join-xor" />
			<xs:element ref="llm" />
			<xs:element ref="state" />
			<xs:element ref="task" />
		</xs:choice>
	</xs:group>
	<xs:group name="task-actions-group">
		<xs:choice>
			<xs:element name="action">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="action-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="task-execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notification">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="task-notification-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="task-execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="task-timer-actions-group">
		<xs:choice>
			<xs:element name="timer-action" type="action-complex-type" />
			<xs:element name="timer-notification" type="task-notification-complex-type" />
			<xs:element minOccurs="0" name="reassignments">
				<xs:complexType>
					<xs:choice>
						<xs:group ref="assignments-group" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="timer-actions-group">
		<xs:choice>
			<xs:element name="timer-action" type="action-complex-type" />
			<xs:element name="timer-notification" type="notification-complex-type" />
		</xs:choice>
	</xs:group>
	<xs:simpleType name="email-address-type">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="execution-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="onEntry" />
			<xs:enumeration value="onExit" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="notification-transport-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="email" />
			<xs:enumeration value="im" />
			<xs:enumeration value="private-message" />
			<xs:enumeration value="push-notification" />
			<xs:enumeration value="user-notification" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="notification-reception-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bcc" />
			<xs:enumeration value="cc" />
			<xs:enumeration value="to" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="role-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="account" />
			<xs:enumeration value="depot" />
			<xs:enumeration value="organization" />
			<xs:enumeration value="regular" />
			<xs:enumeration value="site" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="script-language-type">
		<xs:restriction base="xs:string">
			<xs:pattern value="(drl|function#[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*|groovy|java)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="task-execution-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="onAssignment" />
			<xs:enumeration value="onEntry" />
			<xs:enumeration value="onExit" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="template-language-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="freemarker" />
			<xs:enumeration value="text" />
			<xs:enumeration value="velocity" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="time-scale-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="second" />
			<xs:enumeration value="minute" />
			<xs:enumeration value="hour" />
			<xs:enumeration value="day" />
			<xs:enumeration value="week" />
			<xs:enumeration value="month" />
			<xs:enumeration value="year" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== brianchandotcom/liferay-portal/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/resources/META-INF/definitions/single-approver-update-workflow-definition.xml
<?xml version="1.0"?>

<workflow-definition
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:liferay.com:liferay-workflow_7.4.0 http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd"
>
	<name>Single Approver</name>
	<description>A single approver can approve a workflow content.</description>
	<version>1</version>
	<state>
		<name>created</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						36,
						51
					]
				}
			]]>
		</metadata>
		<initial>true</initial>
		<transitions>
			<transition>
				<name>review</name>
				<target>review</target>
				<default>true</default>
			</transition>
		</transitions>
	</state>
	<state>
		<name>approved</name>
		<metadata>
			<![CDATA[
				{
					"terminal": true,
					"xy": [
						380,
						51
					]
				}
			]]>
		</metadata>
		<actions>
			<action>
				<name>approve</name>
				<status-code>0</status-code>
				<execution-type>onEntry</execution-type>
			</action>
		</actions>
	</state>
	<task>
		<name>update</name>
		<metadata>
			<![CDATA[
				{
					"transitions": {
						"resubmit": {
							"bendpoints": [
								[
									303,
									140
								]
							]
						}
					},
					"xy": [
						328,
						199
					]
				}
			]]>
		</metadata>
		<actions>
			<action>
				<name>deny</name>
				<status-code>4</status-code>
				<priority>1</priority>
				<execution-type>onAssignment</execution-type>
			</action>
			<action>
				<name>pending</name>
				<status-code>1</status-code>
				<priority>2</priority>
				<execution-type>onAssignment</execution-type>
			</action>
			<notification>
				<name>Creator Modification Notification</name>
				<template>
					<![CDATA[Your submission was rejected by ${userName}, please modify and resubmit.]]>
				</template>
				<template-language>freemarker</template-language>
				<notification-type>email</notification-type>
				<notification-type>user-notification</notification-type>
				<recipients receptionType="to">
					<user />
				</recipients>
				<execution-type>onAssignment</execution-type>
			</notification>
		</actions>
		<assignments>
			<user />
		</assignments>
		<transitions>
			<transition>
				<name>resubmit</name>
				<target>review</target>
				<default>true</default>
			</transition>
		</transitions>
	</task>
	<task>
		<name>review</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						168,
						36
					]
				}
			]]>
		</metadata>
		<actions>
			<notification>
				<name>Review Notification</name>
				<template>
					<![CDATA[${userName} sent you a ${entryType} for review in the workflow.]]>
				</template>
				<template-language>freemarker</template-language>
				<notification-type>email</notification-type>
				<notification-type>user-notification</notification-type>
				<recipients receptionType="to">
					<assignees />
				</recipients>
				<execution-type>onAssignment</execution-type>
			</notification>
			<notification>
				<name>Review Completion Notification</name>
				<template>
					<![CDATA[Your submission was reviewed<#if taskComments?has_content> and the reviewer applied the following ${taskComments}</#if>.]]>
				</template>
				<template-language>freemarker</template-language>
				<notification-type>email</notification-type>
				<recipients receptionType="to">
					<user />
				</recipients>
				<execution-type>onExit</execution-type>
			</notification>
		</actions>
		<assignments>
			<roles>
				<role>
					<role-type>depot</role-type>
					<name>Asset Library Administrator</name>
				</role>
				<role>
					<role-type>depot</role-type>
					<name>Asset Library Content Reviewer</name>
				</role>
				<role>
					<role-type>depot</role-type>
					<name>Asset Library Owner</name>
				</role>
				<role>
					<role-type>organization</role-type>
					<name>Organization Administrator</name>
				</role>
				<role>
					<role-type>organization</role-type>
					<name>Organization Content Reviewer</name>
				</role>
				<role>
					<role-type>organization</role-type>
					<name>Organization Owner</name>
				</role>
				<role>
					<role-type>regular</role-type>
					<name>Administrator</name>
				</role>
				<role>
					<role-type>regular</role-type>
					<name>Portal Content Reviewer</name>
				</role>
				<role>
					<role-type>site</role-type>
					<name>Site Administrator</name>
				</role>
				<role>
					<role-type>site</role-type>
					<name>Site Content Reviewer</name>
				</role>
				<role>
					<role-type>site</role-type>
					<name>Site Owner</name>
				</role>
			</roles>
		</assignments>
		<transitions>
			<transition>
				<name>approve</name>
				<target>approved</target>
				<default>true</default>
			</transition>
			<transition>
				<name>reject</name>
				<target>update</target>
				<default>false</default>
			</transition>
		</transitions>
	</task>
</workflow-definition>

=== brianchandotcom/liferay-portal/modules/dxp/apps/ai-hub/ai-hub-site-initializer/src/main/resources/site-initializer/workflow-definitions/change-tone-workflow-definition/workflow-definition.xml
<?xml version="1.0"?>

<workflow-definition
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:liferay.com:liferay-workflow_7.4.0 http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd"
>
	<name>Change Tone</name>
	<description>A writing agent that alters the tone of a text to a specific tone.</description>
	<version>1</version>
	<llm>
		<name>changeTone</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						276,
						242
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				Change Tone
			</label>
		</labels>
		<input-variables>
			<![CDATA[
[
	{
		"name": "text",
		"type": "string"
	},
	{
		"name": "tone",
		"type": "string"
	}
]
]]>
		</input-variables>
		<output-variables>
			<![CDATA[
[
	{
		"name": "rewrittenText",
		"type": "string"
	}
]
]]>
		</output-variables>
		<prompt>
			<![CDATA[You are an expert linguistic editor. Your sole task is to adjust the tone of the provided text to be more {{tone}}. Modify vocabulary, phrasing, and sentence structure as needed while preserving the original meaning, intent, and clarity. If the text already matches this tone, return it unchanged. Output only the rewritten text, with no explanations or commentary.]]>
		</prompt>
		<tools>
			<![CDATA[[]]]>
		</tools>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						End
					</label>
				</labels>
				<name>end</name>
				<target>end</target>
				<default>true</default>
			</transition>
		</transitions>
		<user-message>
			<![CDATA[This is the text whose tone was changed to be {{tone}}: {{text}}]]>
		</user-message>
	</llm>
	<state>
		<name>start</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						273,
						25
					]
				}
			]]>
		</metadata>
		<initial>true</initial>
		<labels>
			<label language-id="en_US">
				Start
			</label>
		</labels>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						Change Tone
					</label>
				</labels>
				<name>changeTone</name>
				<target>changeTone</target>
				<default>true</default>
			</transition>
		</transitions>
	</state>
	<state>
		<name>end</name>
		<metadata>
			<![CDATA[
				{
					"terminal": true,
					"xy": [
						277,
						459
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				End
			</label>
		</labels>
	</state>
</workflow-definition>
